src/appConstants/menu.ts, src/layouts/Footer.tsx, src/layouts/LeftSidebar.tsx, src/layouts/Topbar/data.ts, src/layouts/Topbar/index.tsx
배포용 코드 정리
- 미구현 기능 주석처리
- 향후 기능 구현시 주석 제거, 기능 없앨시 주석처리한 코드 제거 필요
- [] IDE에서 검출되는 모든 경고와 오류를 해결하셨습니까?
=> [release/remove-unnecessary] WBJ-680 배포용 코드 정리

src/components/hooks/useVideoRecorder.ts, src/helpers/api/index.ts, src/helpers/api/member.ts, src/helpers/api/record.ts, src/helpers/api/team.ts, src/helpers/api/whiteboard.ts, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useWhiteboard.ts, src/pages/settings/CreateTeam.tsx, src/pages/settings/hooks/useTeamSettings.tsx, src/redux/auth/saga.ts
API spec 변경사항 반영
- 로그인시 속한 팀 목록 받아오기, id 가장 낮은 팀 기본 팀으로 설정
- readAllxxx parameter에 teamId 추가
- createxxx request body에 teamId 추가
- createProfileImage, createLogoImage API 주소 변경사항 반영
- readAllRecord, readAllWhiteboard response data key값 변경
- 팀 생성 기본 미리보기 사진 추가
- update 관련 PUT/PATCH cors 에러 발생중
- presignedURL 파일/이미지 업로드 관련 PUT 403/405 에러 발생중
=> [fix/api] WBJ-707 API spec 변경사항 반영

src/appConstants/menu.ts, src/helpers/menu.ts, src/layouts/Horizontal/Navbar.tsx, src/layouts/LeftSidebar.tsx, src/pages/settings/hooks/useTeamSettings.tsx, src/pages/settings/types.ts, src/redux/auth/saga.ts
사이드바 팀 리스트 구현
- 사이드바 팀 리스트 구현
- 로그인시 소속 팀 전체 리스트 세션에 저장
- 팀 로고 표시 미구현
=> [feature/teams] WBJ-681 사이드바 팀 리스트 구현

src/appConstants/menu.ts, src/helpers/api/index.ts, src/helpers/api/team.ts, src/helpers/menu.ts, src/layouts/Menu/MenuItem.tsx, src/layouts/Menu/MenuItemLink.tsx
- 사이드바 팀 전환 기능 구현
- 사이드바 팀 전환 기능 구현
=> [feature/teams] WBJ-704 사이드바 팀 전환 기능 구현

src/components/hooks/useVideoRecorder.ts, src/helpers/api/team.ts, src/helpers/menu.ts, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useWhiteboard.ts, src/pages/settings/LeftPanel.tsx, src/pages/settings/hooks/useTeamSettings.tsx
설정 페이지 팀 전환 구현
- 설정 페이지 팀 전환 구현
- 타 API 호출 파라미터 변경
=> [feature/teams] WBJ-705 설정 페이지 팀 전환 구현 

src/helpers/menu.ts, src/layouts/Menu/MenuItem.tsx
OAuth 로그인 후 대시보드 진입 버그 해결
- 사이드바 메뉴 teams 로직 조건 추가
=> [fix/login] WBJ-784 OAuth 로그인 후 대시보드 진입 버그 해결

src/App.tsx, src/components/VideoPlayer/VideoBookmarkAdd.tsx, src/components/VideoPlayer/VideoPlayer.tsx, src/components/VideoPlayer/VideoVolume.tsx
비디오 플레이어 컴포넌트 디자인 / 버그 수정
- 비디오 플레이어 컴포넌트 버튼 디자인 수정
- 비디오 플레이어 control 부분 세부 디자인 수정
- 북마크 add시 form 나타나지 않는 버그 수정
=> [style/video] WBJ-781 비디오 플레이어 컴포넌트 디자인 / 버그 수정

src/components/hooks/useVideoRecorder.ts, src/helpers/api/whiteboard.ts, src/layouts/Horizontal/Navbar.tsx, src/layouts/LeftSidebar.tsx, src/layouts/Menu/MenuItem.tsx, src/layouts/Topbar/index.tsx, src/pages/apps/Whiteboard/Whiteboard.tsx, src/pages/docs/Dashboard.tsx, src/pages/docs/WhiteboardCard.tsx, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useMoment.ts, src/pages/docs/hooks/useWhiteboard.ts, src/pages/settings/hooks/usePersonalSettings.tsx, src/redux/auth/saga.ts
대시보드 버그 수정
- OAuth 로그인 후 대시보드 진입 실패하는 버그 수정 (유저 정보 Redux에서 받아오게 변경)
- 데일리 스탠드업 여러 번 받아오는 버그 수정 (useEffect dependency function에 useCallback 사용)
- 추후 프로필 업데이트, 팀 전환 등 이벤트 발생 시 reducer 추가 필요
=> [fix/bugs] WBJ-793 대시보드 버그 수정

src/components/VideoPlayer/VideoPlayer.tsx, src/helpers/api/index.ts, src/helpers/api/record.ts, src/pages/docs/DailyStandupCard.tsx, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/types.ts
비디오 플레이어 로딩 로직 개선
- useDailyStandups에서 비디오 element 일괄 생성하는 방식에서 모달 클릭 시 개별 로드하는 방식으로 변경
- 로딩 스피너 추후 추가 예정
=> [refactor/video-loading] WBJ-788 비디오 플레이어 로딩 로직 개선

src/components/hooks/useVideoRecorder.ts, src/helpers/api/apiCore.ts, src/helpers/api/index.ts, src/helpers/api/member.ts, src/helpers/api/team.ts, src/helpers/menu.ts, src/layouts/LeftSidebar.tsx, src/layouts/Menu/MenuItem.tsx, src/pages/account/hooks/useOAuthLogin.ts, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useWhiteboard.ts, src/pages/settings/CreateTeam.tsx, src/pages/settings/CreateTeamImageForm.tsx, src/pages/settings/LeftPanel.tsx, src/pages/settings/TeamImageForm.tsx, src/pages/settings/TeamSettings.tsx, src/pages/settings/hooks/usePersonalSettings.tsx, src/pages/settings/hooks/useTeamSettings.tsx, src/redux/actions.ts, src/redux/reducers.ts, src/redux/sagas.ts, src/redux/team/actions.ts, src/redux/team/constants.ts, src/redux/team/reducers.ts, src/redux/team/saga.ts
개인 설정 버그 수정, 팀 설정 버그 수정, 팀 생성 버그 수정
- 개인 프로필 update API 버그 수정
- 팀 create, update 버그 수정
- 팀 전환 버그 수정
- 팀 생성시 이미지 프리뷰 버그 수정
- 팀 관련 Redux 구현
=> [fix/settings] WBJ-811, WBJ-812, WBJ-813, WBJ-814, WBJ-844 설정 페이지 관련 버그 수정

src/helpers/api/index.ts, src/helpers/api/team.ts, src/pages/settings/TeamSettings.tsx, src/pages/settings/hooks/useTeamSettings.tsx, src/redux/team/actions.ts, src/redux/team/constants.ts, src/redux/team/reducers.ts, src/redux/team/saga.ts
=> [feature/teams] WBJ-842 팀 떠나기 기능 구현

.env, src/pages/apps/Whiteboard/Whiteboard.tsx
yorkie-tldraw를 Yorkie SaaS와 연결하였으며, 다른 화이트보드로 진입해도 이전 화이트보드가 보이는 버그를 해결하였습니다.
- 기존 Asyncrum Yorkie Server에서, Yorkie SaaS로 Yorkie API를 변경하였으며, Yorkie SaaS를 위한 `apiKey`가 추가되었습니다.
- `Whiteboard` 컴포넌트가 refresh되지 않아, 다른 화이트보드로 진입해도 이전 화이트보드가 보이는 현상을 해결하였습니다.
- `Whiteboard` 컴포넌트에 id에 대한 `useEffect` dependency가 추가되었습니다. 
X
=> [feature/yorkie-tldraw] yorkie-tldraw 업데이트 및 화이트보드 변경 관련 버그 해결

src/helpers/api/record.ts, src/pages/docs/hooks/useDailyStandup.ts, src/redux/team/saga.ts
데일리 스크럼 Seen 재구현, 팀 멤버 표시 버그 수정
- Seen 목록 갱신을 위한 record update API 변경사항 반영
- 설정 페이지 팀 멤버 보이지 않는 버그 수정
=> [feature/record] WBJ-843 데일리 스크럼 Seen 재구현, 팀 멤버 표시 버그 수정

src/pages/docs/WhiteboardCard.tsx
Yorkie Document ID 네이밍 방식을 변경하였습니다.
- `WhiteboardCard.tsx`: 기존 `whiteboard.id`에서 `currentTeam.code + '-' + whiteboard.id`로 네이밍 방식을 변경하였습니다.
=> [feature/yorkie-doc] Yorkie Document ID 네이밍 방식 변경

.env, src/appConstants/menu.ts, src/helpers/api/index.ts, src/helpers/api/team.ts, src/helpers/menu.ts, src/pages/apps/Meeting/Meeting.tsx, src/pages/docs/CreateMeetingButton.tsx, src/pages/docs/Dashboard.tsx, src/pages/docs/MeetingCard.tsx, src/pages/docs/MeetingContainer.tsx, src/pages/docs/hooks/index.ts, src/pages/docs/hooks/useMeeting.ts, src/pages/docs/hooks/useMeetingCard.ts, src/redux/team/actions.ts, src/redux/team/constants.ts, src/redux/team/reducers.ts, src/redux/team/saga.ts, src/routes/index.tsx
미팅 관련 기능 구현
- 대시보드 미팅 섹션 추가
- 미팅 API 연동
- 사이드바 메뉴 리스트 변경
=> [feature/meeting] WBJ-839, WBJ-840, WBJ-841 미팅 관련 기능 구현

src/pages/account/OAuth.tsx, src/pages/account/hooks/useOAuthLogin.ts, src/pages/docs/MeetingContainer.tsx, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useMeeting.ts, src/pages/docs/hooks/useWhiteboard.ts, src/redux/auth/saga.ts, src/redux/team/saga.ts
Redux-saga API 다중 호출 버그 수정
- OAuth, 팀 관련 Redux-saga API 다중 호출 버그 수정
=> [fix/redux] Redux-saga API 다충 호출 버그 수정

src/assets/scss/config/saas/_variables.scss, src/components/CardTitle.tsx, src/components/ChatList/ChatForm.tsx, src/components/ChatList/ChatList.tsx, src/components/ChatList/hooks/index.ts, src/components/ChatList/hooks/useChatForm.ts, src/components/ChatList/hooks/useChatList.ts, src/components/ChatList/index.tsx, src/components/CommentVideoRecorder.tsx, src/components/CreateCommentRecordButton.tsx, src/components/VideoPlayer/Comment.ts, src/components/VideoPlayer/VideoBookmark.ts, src/components/VideoPlayer/VideoBookmarkShow.tsx, src/components/VideoPlayer/VideoBookmarkTimeline.tsx, src/components/VideoPlayer/VideoPlayer.tsx, src/components/hooks/index.ts, src/components/hooks/useCommentVideoRecorder.ts, src/components/index.tsx, src/helpers/api/comment.ts, src/helpers/api/index.ts, src/pages/docs/DailyStandupCard.tsx
북마크에서 자동 재생 영상 기반의 쓰레드를 구현하였습니다.
- `helpers/api/comment.ts`: 쓰레드를 위한 Comment 도메인의 API를 구성하였습니다.
- `components/ChatList`: Chat 기반 컴포넌트를 템플릿에서 가져와 북마크 쓰레드에 맞도록 변형하여 구성하였습니다.
- `components/OOOCommentOOO`: 쓰레드에 댓글을 달기 위한 영상 녹화 등의 컴포넌트들을 기존 Recorder 컴포넌트들을 변형하여 구성하였습니다.
- VideoPlayer Modal 위에서 영상 녹화 Modal을 띄우기 위해서, SCSS variables의 modal `z-index`를 videoPlayer의 `z-index`보다 크도록 변경하였습니다.
- 추가 사항
- 북마크 쓰레드 댓글의 삭제 등은 구현되어 있지 않습니다. 
- 북마크 쓰레드 스크린샷
=> [feature/bookmark-thread] 북마크 자동 재생 쓰레드 구현

src/assets/scss/config/saas/_variables.scss, src/components/CardTitle.tsx, src/components/ChatList/ChatForm.tsx, src/components/ChatList/ChatList.tsx, src/components/ChatList/hooks/index.ts, src/components/ChatList/hooks/useChatForm.ts, src/components/ChatList/hooks/useChatList.ts, src/components/ChatList/index.tsx, src/components/CommentVideoRecorder.tsx, src/components/CreateCommentRecordButton.tsx, src/components/VideoPlayer/Comment.ts, src/components/VideoPlayer/VideoBookmark.ts, src/components/VideoPlayer/VideoBookmarkShow.tsx, src/components/VideoPlayer/VideoBookmarkTimeline.tsx, src/components/VideoPlayer/VideoPlayer.tsx, src/components/hooks/index.ts, src/components/hooks/useCommentVideoRecorder.ts, src/components/index.tsx, src/helpers/api/apiCore.ts, src/helpers/api/comment.ts, src/helpers/api/index.ts, src/pages/docs/DailyStandupCard.tsx
Access Token이 만료되었을 때 Access Token을 재발급받는 Refresh Token 기능을 구현하였으며, apiCore 버그를 수정하였습니다.
- `helpers/api/apiCore.ts`
- refreshToken API를 호출하는 `refreshToken()` 함수와, 세션에 저장된 Access Token을 갱신하는 `renewAccessTokenInSession()` 함수를 구현하였습니다.
- get API에서, param이 null로 들어오면 token을 보내지 않는 로직을 수정하였습니다.
- `httpOnly`로 저장된 Refresh Token Cookie을 request로 보내기 위해, `axios.defaults.withCredentials = true;` 옵션을 설정하였습니다.
- 추가 사항
- `refreshToken()` 함수의 `axios.get()`에만 `withCrendentials: true` 파라미터를 주는 경우 httpOnly Cookie를 보내지 않는 현상이 발생합니다. 이후에 원인 파악이 필요합니다.
=> [feature/refresh-token] Refresh Token 기능 구현 및 버그 수정

purgecss.config.js
PurgeCSS 모달 버그 수정
PurgeCSS config safelist에 모달 관련 태그 prefix regex 추가
=> [fix/purgecss] WBJ-949 PurgeCSS 모달 버그 수정

src/layouts/Menu/MenuItemWithChildren.tsx
팀 리스트 Default 열린 상태로 만들기
- 팀 리스트 Default 열린 상태로 만들기
<초기 화면>
=> [fix/sidebar] WBJ-955 팀 리스트 Default 열린 상태로 만들기

src/appConstants/menu.ts, src/helpers/menu.ts, src/layouts/LeftSidebar.tsx, src/layouts/Menu/MenuItem.tsx, src/layouts/Menu/MenuItemWithChildren.tsx, src/layouts/Menu/index.tsx, src/layouts/RightSidebar.tsx, src/layouts/Topbar/NotificationDropdown.tsx, src/layouts/Topbar/ProfileDropdown.tsx, src/layouts/Topbar/index.tsx
사이드바 메뉴 변경
- 사이드바 메뉴에 설정, 로그아웃 추가
- 우측 상단 프로필 누르면 설정 페이지로 redirect
- 탑바 아이콘 변경
<사이드바>
<탑바>
=> [style/sidebar] WBJ-950 사이드바 메뉴 변경

package.json, src/pages/settings/PersonalInfoForm.tsx, src/pages/settings/hooks/usePersonalSettings.tsx, yarn.lock
개인 프로필 타임존 설정 기능 구현
- 개인 프로필 타임존 설정 기능 구현
- 개인 프로필 변경 form에서 기존엔 이름이 필수 항목이였지만 현재는 빈 칸으로 남겨두고 Save Changes 버튼 누를 시 이름 변경하지 않는 방식으로 변경
=> [feature/timezone] WBJ-946 개인 프로필 타임존 설정

package.json, src/appConstants/menu.ts, src/helpers/menu.ts, src/layouts/Horizontal/Menu/MenuItemLink.tsx, src/layouts/Horizontal/Navbar.tsx, src/layouts/LeftSidebar.tsx, src/layouts/Menu/MenuItemLink.tsx, yarn.lock
사이드바 팀원 타임존 표시
- 사이드바 팀원 타임존 표시
=> [feature/sidebar] WBJ-947 사이드바 팀원 타임존 표시

src/pages/docs/Dashboard.tsx, src/pages/docs/NewTeamContainer.tsx, src/redux/auth/saga.ts
팀 없을 때 대시보드에 팀 생성 컴포넌트 추가
- 팀 없을 때 대시보드에 팀 생성 컴포넌트 추가
=> [feature/dashboard] WBJ-957 팀 없을 때 대시보드에 팀 생성 컴포넌트 추가

src/components/ScreenRecorder.tsx, src/components/hooks/useVideoRecorder.ts, src/helpers/api/apiCore.ts, src/helpers/api/index.ts, src/helpers/api/meeting.ts, src/helpers/api/team.ts, src/pages/docs/CreateMeetingButton.tsx, src/pages/docs/DailyStandupCard.tsx, src/pages/docs/MeetingCard.tsx, src/pages/docs/MeetingContainer.tsx, src/pages/docs/hooks/useDailyStandup.ts, src/pages/docs/hooks/useMeeting.ts, src/pages/docs/hooks/useMeetingCard.ts, src/pages/docs/types.ts, src/redux/team/actions.ts, src/redux/team/constants.ts, src/redux/team/reducers.ts, src/redux/team/saga.ts
실시간 회의 기능 개선
- Meetings API 백엔드와 Sync
- MeetingCard UI 개선
- 회의 생성하는 사람: 회의 생성 -> 녹화 여부 선택 -> (녹화 선택 시) 녹화 시작 -> 회의 링크 진입 -> (녹화 선택 시) 녹화 종료, 저장 및 회의 종료 순서로 진행
- 회의 참여자: 회의 status가 true면 회의 창 오픈, false면 회의 녹화 재생
<MeetingCard>
<MeetingCard - Dropdown>
<회의 생성>
<녹화 여부 선택>
<회의 시작>
<녹화 종료, 저장 & 회의 종료>
=> [feature/meeting] WBJ-948 미팅 기능 개선

src/pages/docs/MeetingCard.tsx, src/pages/docs/MeetingContainer.tsx, src/pages/docs/hooks/useMeeting.ts
Meeting 카드 참여자 프로필 사진 추가
- Meeting 카드 참여자 프로필 사진 추가
- Meeting type 수정
=> [feature/meeting] Meeting 카드 참여자 프로필 사진 추가

public/index.html, src/helpers/menu.ts, src/layouts/Footer.tsx, src/layouts/Menu/MenuItem.tsx, src/layouts/Menu/MenuItemLink.tsx, src/layouts/Menu/index.tsx, src/layouts/Topbar/index.tsx, src/pages/account/AccountLayout.tsx, src/pages/docs/DailyStandupCard.tsx, src/pages/docs/DailyStandupContainer.tsx, src/pages/docs/MeetingCard.tsx, src/pages/docs/WhiteboardCard.tsx, src/pages/docs/WhiteboardContainer.tsx, src/pages/error/PageNotFound.tsx, src/pages/error/ServerError.tsx, src/pages/settings/LeftPanel.tsx, src/redux/layout/reducers.ts
스타일 세부 개선
- 사이드바 메뉴 간격, 위치 조정
- 탑바 다크 모드 토글 추가
- 대시보드 컴포넌트 간격 조정
- 미팅 라이브 뱃지 아이콘 추가
- 화이트보드 read more 표시 기준 수정
- 사이드바 activeItem 오류 수정
- Footer 내용 수정
=> [style/overall] WBJ-982 스타일 세부 개선

src/assets/scss/Saas.scss, src/components/VideoPlayer/TimeControl.tsx, src/components/VideoPlayer/VideoPlayer.tsx, src/components/VideoRecorder.tsx, src/pages/docs/DailyStandupCard.tsx
비디오 플레이어 캠 비디오 표시 구현
- 비디오 플레이어 캠 비디오 표시 구현
=> [feature/video] 비디오 플레이어 캠 비디오 표시 구현
